# Author : Singappuli Arachchige Eranga Lakmal Perera
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  strategy:                               
    type: RollingUpdate         
    rollingUpdate:
      maxSurge: 1              
      maxUnavailable: 0  
  progressDeadlineSeconds: 600
  minReadySeconds: 0            
  revisionHistoryLimit: 5        
  template:
    metadata:
      labels:
        app: webapp
    spec:
      terminationGracePeriodSeconds: 15
      containers:
      - name: webapp
        image: sael1988/bluesky-k8s-demo:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  