# Author : Singappuli Arachchige Eranga Lakmal Perera
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: sael1988/bluesky-k8s-demo:1.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

        livenessProbe:
          httpGet:
            path: /bluesky
            port: 8080
          failureThreshold: 1
          periodSeconds: 5

        startupProbe:
          httpGet:
            path: /bluesky
            port: 8080
          failureThreshold: 5
          periodSeconds: 3


---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  