# Author: Singappuli Arachchige Eranga Lakmal Perera

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: bluesky-cluster   
  GKE_ZONE: us-west1-a
  GKE_BLUE_SVC_IP: None
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build
      run: mvn -B package --file SpringbootApp/pom.xml
    - name: list directories
      run: ls -al SpringbootApp/target/
    - name: docker build
      run: docker build SpringbootApp/ -t sael1988/bluesky-k8s-demo:1.0.18
    - name: login to the docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: push image
      uses: docker/build-push-action@v2
      with:
        context: ./SpringbootApp
        push: true
        tags: sael1988/bluesky-k8s-demo:1.0.18

    - name: Checkout
      uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SECRET }}
        project_id: ${{ secrets.GKE_PROJECT}}
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    - name: Deploy
      run: |-
        kubectl apply -f k8s/





  


      

      
